### ISSUE TITLE
MKDropdownMenu in UIScrollView

### ISSUE THREAD

**Issue by ghost** [maxkonovalov/MKDropdownMenu#1]
Выпадающие элементы не прикреплены к заголовку. 
В UIScrollView появляется проблема -  элементы висят на месте, заголовок движется.
![img_1119](https://cloud.githubusercontent.com/assets/5567704/15185338/b00bee2a-17a9-11e6-9033-915084a709b9.PNG)
![img_1120](https://cloud.githubusercontent.com/assets/5567704/15185340/b03b309a-17a9-11e6-97c8-d145fc68a09a.PNG)
Вы можете исправить это?
Заранее спасибо!

**Comment by maxkonovalov** [comment]
@fspacebp Да, как раз планирую исправить это в ближайшем релизе ;)

**Comment by ghost** [comment]
Отлично) как скоро вы планируете ближайший релиз?

**Comment by maxkonovalov** [comment]
Через пару недель, раньше вряд ли...

**Comment by ghost** [comment]
Хорошо, спасибо, буду ждать

**Comment by maxkonovalov** [comment]
@fspacebp В версии `1.1` добавлена поддержка UIScrollView. 
Для того, чтобы меню скроллилось вместе с остальным контентом, нужно установить scroll view в качестве параметра `presentingView`, например:

``` objc
self.dropdownMenu.presentingView = self.tableView;
```

**Comment by ghost** [comment]
Прошло всего 3 дня) Большое вам спасибо!

**Comment by EddieLukeAtmey** [comment]
Hi Max,

Can you also put `IBOutlet` to `presentingView` please? That way we can connect directly to the IB without having set it with the code. Thanks

**Comment by maxkonovalov** [comment]
Hey @EddieLukeAtmey,
Sure, will do the addition, along with other fixes soon!

**Comment by maxkonovalov** [comment]
Added `IBOutlet` to `presentingView`, thanks @EddieLukeAtmey - nice catch :)
