### ISSUE TITLE
selectRow not called programmtically why?

### ISSUE THREAD

**Issue by oduysmara** [maxkonovalov/MKDropdownMenu#10]
selectRow as method it is not called  if i call it programmatically why?

I need response ASAP

This  is my code:

 [_users reloadAllComponents];
    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, 3* NSEC_PER_SEC), dispatch_get_main_queue(), ^{
        [_users bringDropdownViewToFront];
        [_users selectRow:18 inComponent:0];
    });

**Comment by maxkonovalov** [comment]
Hi @oduysmara!

`-selectRow:inComponent:` only updates the rows returned by `-selectedRowsInComponent:` and, in case the component is currently open, triggers the corresponding menu rows update (your delegate methods like `titleForRow:`, `viewForRow:`, etc. should be called). Note that the delegate method `-dropdownMenu:didSelectRow:inComponent:` only called when you tap the row in a currently opened component, but never when calling `selectRow`.

For your case, if you rely on the menu's selected rows, you should call the `-(de)selectRow:inComponent:` manually to mark the rows selected/unselected, and provide the corresponding visual logic in one of the above delegate methods. If you want to handle some action, just call the corresponding logic manually from the place where you mark the row as selected.

Let me know if it helped, and provide more details on your case if you need further assistance.
