### ISSUE TITLE
disclosureIndicatorImage Color

### ISSUE THREAD

**Issue by oduysmara** [maxkonovalov/MKDropdownMenu#11]
how to change color for disclosureIndicatorImage?

**Comment by maxkonovalov** [comment]
If you want to use the built-in triangle image, simply set the `tintColor` of the menu like this: 
```objc
self.dropdownMenu.tintColor = [UIColor redColor];
```

If you want to use a custom image, set the `disclosureIndicatorImage` property to your custom image. To make it also respect the `tintColor` property, provide an image with "Always Template" rendering mode:
```objc
UIImage *indicator = [[UIImage imageNamed:@"indicator"]
                      imageWithRenderingMode:UIImageRenderingModeAlwaysTemplate];
self.dropdownMenu.disclosureIndicatorImage = indicator;
```
