### ISSUE TITLE
How to change arrow icon

### ISSUE THREAD

**Issue by Jabjai** [maxkonovalov/MKDropdownMenu#15]
Hello, I want to change arrow colour of dropdown. By default it has a blue colour and I want to change its to another colour.

Please help me.
Thank you very much.

**Comment by maxkonovalov** [comment]
Hello @Jabjai 
You can change the arrow color by setting the `tintColor` property of the menu (same as UIButton).
Alternatively, you can set your custom image using the `disclosureIndicatorImage` property.
