### ISSUE TITLE
Change component title textcolor

### ISSUE THREAD

**Issue by saintjab** [maxkonovalov/MKDropdownMenu#2]
Great library. How can I change the textcolor of the component. Its now blue and also where I can access the (blue) triangle? I want to change it too. Thanks

**Comment by maxkonovalov** [comment]
Hey @saintjab! To change the title text color of the component, you can use `-dropdownMenu:attributedTitleForComponent:` delegate method and provide an attributed string with whatever properties you want to customize. Just like `UIPickerView` 😉

``` objc
- (NSAttributedString *)dropdownMenu:(MKDropdownMenu *)dropdownMenu attributedTitleForComponent:(NSInteger)component {
    return [[NSAttributedString alloc] initWithString:@"TITLE"
                                           attributes:@{NSForegroundColorAttributeName: [UIColor darkTextColor]}];
}
```

The most simple way to customize the component's disclosure triangle is to set the `tintColor` of the `MKDropdownMenu` to the desired color. If you also want to change the shape of the triangle itself, you can provide your custom image via the menu's `disclosureIndicatorImage` property. Note that by default it uses `UIImageRenderingModeAlwaysTemplate` for rendering.

``` objc
dropdownMenu.disclosureIndicatorImage = [UIImage imageNamed:@"indicator"];
```

You can see all the above code in action in the example app. If you have some other questions feel free to ask. I hope you enjoy using this control 😀

**Comment by saintjab** [comment]
Thanks. Its working now. :)
