### ISSUE TITLE
DropdownMenu show selections on top of control

### ISSUE THREAD

**Issue by EddieLukeAtmey** [maxkonovalov/MKDropdownMenu#21]
Hi Max, the dropdown with your support has been a great help! Thanks for your work.
Now I've got a request: I'd like to achieve something like the ss below:

![screen shot 2017-03-10 at 11 52 20](https://cloud.githubusercontent.com/assets/10751944/23782580/0e1750a0-0588-11e7-8470-0e41488a221a.png)

So, instead of showing selections down as it does now, how can I make it shows up? Please suggest me a way to achieve this.

**Comment by maxkonovalov** [comment]
Hi @EddieLukeAtmey! 

This shouldn't be too hard to implement, you can take a look at `MKDropdownMenuTransition` class – it handles all the presentation and layout logic for the menu. You simply need to assign the `self.controller.view.frame` a different value and also tweak the `CGAffineTransform` for the animation a little.

If you implement this feature, feel free to add a pull request, it's a really welcome addition!
I'm very pressed on time right now, so won't be able to make a lot of things here, but I'll be happy to help if you got questions ;)

Cheers)

**Comment by maxkonovalov** [comment]
The feature is now available in [1.4](https://github.com/maxkonovalov/MKDropdownMenu/releases/tag/1.4)
Thanks again @EddieLukeAtmey for the addition 👏
