### ISSUE TITLE
why text is not wrapping in row

### ISSUE THREAD

**Issue by ParveshChauhan** [maxkonovalov/MKDropdownMenu#28]
how to wrap text in row. When text length is more then width of dropdown menu ,text is truncated.

**Comment by maxkonovalov** [comment]
Hi @ParveshChauhan, the basic implementation allows a single-line text with plain or attributed strings. For all custom setups please use ```- (UIView *)dropdownMenu:(MKDropdownMenu *)dropdownMenu viewForRow:(NSInteger)row forComponent:(NSInteger)component reusingView:(nullable UIView *)view;```
