### ISSUE TITLE
change component name

### ISSUE THREAD

**Issue by cristinaITdeveloper** [maxkonovalov/MKDropdownMenu#4]
Hi, nice library!
I would like to change the component name when the row is selected. How can I do it?
Thank you

**Comment by maxkonovalov** [comment]
Hi @LadyDeveloper!
Pleased to know that you like the lib)

You can change the selected component's title simply by implementing one of the following delegate methods:

``` objc
- (nullable NSString *)dropdownMenu:(MKDropdownMenu *)dropdownMenu titleForSelectedComponent:(NSInteger)component;
```

or

``` objc
- (nullable NSAttributedString *)dropdownMenu:(MKDropdownMenu *)dropdownMenu attributedTitleForSelectedComponent:(NSInteger)component;
```

**Comment by cristinaITdeveloper** [comment]
Thank's for reply, but I would like to change the component name, with the name of row, when I select the row.

**Comment by maxkonovalov** [comment]
@LadyDeveloper  For that case, just keep track of your selected row and in the delegate method return the appropriate title depending on the selection state, for example:

``` objc
- (nullable NSString *)dropdownMenu:(MKDropdownMenu *)dropdownMenu titleForRow:(NSInteger)row forComponent:(NSInteger)component {
    return (_selectedRow == row) ? @"Selected Title" : @"Title";
}
```

And you need to reload the component when its row has been selected:

``` objc
- (void)dropdownMenu:(MKDropdownMenu *)dropdownMenu didSelectRow:(NSInteger)row inComponent:(NSInteger)component {
    _selectedRow = row;
    [dropdownMenu reloadComponent:component];
}
```

For more complex scenarios with multiple selections, etc. you can use the following convenience methods in MKDropdownMenu:

``` objc
- (void)selectRow:(NSInteger)row inComponent:(NSInteger)component;
- (void)deselectRow:(NSInteger)row inComponent:(NSInteger)component;
- (NSIndexSet *)selectedRowsInComponent:(NSInteger)component;
```

But note that you need to explicitly select/deselect the rows by calling the above methods in `-dropdownMenu:didSelectRow:inComponent:` or elsewhere depending on your needs.

**Comment by cristinaITdeveloper** [comment]
Thank you!

**Comment by maxkonovalov** [comment]
You're welcome :)
I'm closing this issue now. If you have more questions, feel free to ask!

**Comment by kahantle** [comment]
Hi maxkonovalov,

This drop down is great but now I want to implement multiple selection in drop down. So how can I achieve this?

Please help me in this.
