### ISSUE TITLE
text cell size to fit problem?

### ISSUE THREAD

**Issue by fukemy** [maxkonovalov/MKDropdownMenu#40]
Hello, I run your example and change some text for row of table. Then got that problem:
![simulator screen shot - iphone 5s - 2017-11-11 at 00 35 25](https://user-images.githubusercontent.com/8202437/32671012-551e79c2-c678-11e7-99ed-ac8a9430ebb9.png)

I think u used size to fit method to label text or something like that but i can not find the code. Plz help me how to make text become clipped like "đasadasdasd..." . Thanks # # @ @maxkonovalov @IvanivOleg

**Comment by fukemy** [comment]
Hi. I found the answer for my question by using 

(nullable NSAttributedString *)dropdownMenu:(MKDropdownMenu *)dropdownMenu attributedTitleForComponent:(NSInteger)component
--

But i can not attribute to make text become "dsadads..." and do not decrease it size. Can you help me attribute name for it? I do not know the key for search google

**Comment by fukemy** [comment]
i used this method but it's seem not working:

- (NSAttributedString *)dropdownMenu:(MKDropdownMenu *)dropdownMenu attributedTitleForComponent:(NSInteger)component {
    NSMutableParagraphStyle *st = [[NSMutableParagraphStyle alloc] init];
    st.lineBreakMode = NSLineBreakByTruncatingTail;
    NSAttributedString *nt =  [[NSAttributedString alloc] initWithString:self.componentTitles[component]
                                           attributes:@{NSFontAttributeName: [UIFont systemFontOfSize:16 weight:UIFontWeightLight],
                                                        NSParagraphStyleAttributeName : st,
                                                        NSForegroundColorAttributeName: self.view.tintColor}];
    return nt;
}

**Comment by fukemy** [comment]
I modify your cell class, it work but it's still not satisfied.
 can u check it?

#import "ShapeSelectView.h"

@implementation ShapeSelectView

- (void)awakeFromNib {
    [super awakeFromNib];
    self.shapeView.fillColor = [UIColor clearColor];
    self.shapeView.strokeColor = self.textLabel.textColor;
    self.shapeView.lineWidth = 1;
    self.textLabel.numberOfLines = 0;
    self.textLabel.lineBreakMode = NSLineBreakByWordWrapping;
}


![simulator screen shot - iphone 5s - 2017-11-11 at 01 07 48](https://user-images.githubusercontent.com/8202437/32672194-c050e8a2-c67c-11e7-99c8-3e7fd314ce51.png)

**Comment by IvanivOleg** [comment]
@fukemy Looks like the default adjustsFontSizeToFitWidth property value of that label is YES. If you want to change it go to the ShapeSelectView.m and add the next line of code into the awakeFromNib method:
`self.textLabel.adjustsFontSizeToFitWidth = NO;`

**Comment by maxkonovalov** [comment]
Hi, @fukemy!

The `ShapeSelectView` is just an example of a custom view for menu rows, you can set up your own view the way you like.

You can customize the height of the rows for each menu component using the delegate method `- (CGFloat)dropdownMenu:(MKDropdownMenu *)dropdownMenu rowHeightForComponent:(NSInteger)component`, but please note that varying row heights within a single component are not supported at the moment.

**Comment by fukemy** [comment]
thanks @IvanivOleg Iva and @maxkonovalov . I used my own view and it work like expected :). + 1 for great lib
