### ISSUE TITLE
Max row number or max menu height ?

### ISSUE THREAD

**Issue by BeQuietLee** [maxkonovalov/MKDropdownMenu#41]
Hello, I found this lib recently, and it helped me quite a lot !
However, I'm wondering that how could I set the max row number to display ( or max menu height ) ?
So that if the row number exceeds the limit, the items can be scrolled in the menu.

**Comment by BeQuietLee** [comment]
Hi there, I have found the solution.
Just overwrite this method, which returns the max num of  shown rows in menu:
- (NSInteger) dropdownMenu:(MKDropdownMenu *)dropdownMenu maximumNumberOfRowsInComponent:(NSInteger)component

**Comment by selini** [comment]
I have try it like that but do not work. I have 30 items in dropdown and i can see only three.

```
-(NSInteger) dropdownMenu:(MKDropdownMenu *)dropdownMenu maximumNumberOfRowsInComponent:(NSInteger)component{
	return 5;
}
```
