### ISSUE TITLE
Add 3 variable in the list row 

### ISSUE THREAD

**Issue by MahmoudAbunaji** [maxkonovalov/MKDropdownMenu#42]
How can i add 3 variable in each row in my component list , And each variable has it's own specification , All of the 3 variables is strings but with different color .

**Comment by maxkonovalov** [comment]
Hello @MahmoudAbunaji 
You can use `- (nullable NSAttributedString *)dropdownMenu:(MKDropdownMenu *)dropdownMenu attributedTitleForRow:(NSInteger)row forComponent:(NSInteger)component` to provide an attributed string for every component. 
Alternatively, you can use `- (UIView *)dropdownMenu:(MKDropdownMenu *)dropdownMenu viewForRow:(NSInteger)row forComponent:(NSInteger)component reusingView:(nullable UIView *)view` to provide a custom view that you can set up the way you like.
