### ISSUE TITLE
Drop down arrow image

### ISSUE THREAD

**Issue by CripyIce** [maxkonovalov/MKDropdownMenu#45]
Hi everyone,
I am trying to remove the drop down arrow completely without any luck.
I tried to make an image 1X1 pixels with transparent background, a 1X1 pixels white image and nothing helps - it ignores it!
If removing it can't be done, than putting a custom coloured arrow.
Thanks!

**Comment by maxkonovalov** [comment]
Hi @CripyIce, did you try setting `self.dropdownMenu.disclosureIndicatorImage = [UIImage new];`? I just tried this in the demo project and it worked as expected.

**Comment by CripyIce** [comment]
Hi @maxkonovalov, thanks for the fast reply!
I tried `dropdownMenu.disclosureIndicatorImage = nil;`, but of course i will try your code!
I will update you when I try it :)

**Comment by CripyIce** [comment]
Hi @maxkonovalov , it worked perfectly!
Thanks man 👍
