### ISSUE TITLE
row methods (viewForRow, titleForRow, attTitleForRow) not getting called

### ISSUE THREAD

**Issue by ghost** [maxkonovalov/MKDropdownMenu#48]
Hi, Ive used this awesome library for a couple of projects before and worked great, right now Im trying to implement a dropdown in a viewcontroller and the viewForRow is not getting called.

I know that because Ive nslog inside it and I can see it never gets called.

Im using viewForComponent for the same component and thats working fine.

Ive tried assigning delegate and datasource via interface builder and programatically and nothing, I just dont know whats happening. Also tried calling attributedStringForRow and nothing.

**Comment by oenama** [comment]
Any updates?  @karlolopez @maxkonovalov 

I used this instead : 

  func dropdownMenu(_ dropdownMenu: MKDropdownMenu, attributedTitleForComponent component: Int) -> NSAttributedString? {
}

**Comment by ghost** [comment]
I was declarating the delegates in a ViewController presented as a popup view with https://github.com/jmascia/KLCPopup library. Somehow this affected and I figured out changing the delegate in root presentation controller. 

In few words, it was not a library issue, so Im closing.
