### ISSUE TITLE
How to set border's property to dropDown?

### ISSUE THREAD

**Issue by EddieLukeAtmey** [maxkonovalov/MKDropdownMenu#6]
My designer clearly want the dropDown like this:

![design](https://cloud.githubusercontent.com/assets/10751944/18345566/4243138c-75e6-11e6-97ab-f2894f41838d.png)

But since I can't find how to set border to the dropDown, it turns out like this:
![actual](https://cloud.githubusercontent.com/assets/10751944/18345565/4242d02a-75e6-11e6-80bc-c48c5996911d.png)

(Please don't mind the data, just the UI and views and stuffs like that.)

I'd love to set border's properties to the sub `tableView` inside the containerController. Please guide me how to. Thanks in advance.

**Comment by maxkonovalov** [comment]
Could you please provide the screenshots for both closed and open states of the menu, so that I can figure out your needs. 
Are you okay with the look of the current menu control itself and only need to add a border to the dropdown when it's shown? Did I get it right?

**Comment by EddieLukeAtmey** [comment]
Yup, you're quite right. As for the closed state, just imagine the view with the green arrow pointing downward, no table below. 

For confirmation, yeah, I'd like to be able to set border's properties to the view below the dropDownView (the table below the view with green arrow). 

For addition, I'd like to be able to control the arrow image, too. Like, keep it constant (don't animate up/down), or might be able to set its pointing direction with `dropDown` states (like, closed => point right, opened => point down). This is just a minor request, so I think I won't create new issue about this.

**Comment by maxkonovalov** [comment]
@EddieLukeAtmey, check out the latest release, I added the `dropdownShowsBorder` and `disclosureIndicatorSelectionRotation` properties, they should fulfil your needs.

To add a border simply set the property as follows:

``` objc
dropdownMenu.dropdownShowsBorder = YES;
```

Note that the color of the border is the same as row separators.

For the arrow image rotation, you can now set the target angle for selected component's disclosure indicator. Setting the `disclosureIndicatorSelectionRotation` to `0` will prevent the image from rotating, and to rotate it left or right use `M_PI_2` or `-M_PI_2` values.

**Comment by EddieLukeAtmey** [comment]
Hi, there's an issue with the `dropdownShowsBorder` in line 752~756:

```
if (self.showsBorder && indexPath.row == self.rowsCount - 1) {
        cell.separatorInset = UIEdgeInsetsMake(0, CGRectGetWidth(tableView.bounds), 0, 0);
} else {
        cell.separatorInset = UIEdgeInsetsZero;
}
```

I'm not sure why you have to set `seperatorInset` to the last row when showing border, but it seems to crop the data inside the cell and my label turn from any to "..." string. 

I've tried comment out everything except `cell.separatorInset = UIEdgeInsetsZero;` and it turns out fine.

Also, there seems to have a problem with `rowSeparatorColor`, as it affect the border color but doesn't to the seperator (image below).
![image](https://cloud.githubusercontent.com/assets/10751944/23156028/dbfe638a-f847-11e6-8846-230177753799.png)

Though I agree that the border color should be the same as the separator's, please do something with these, thanks!!!
(I was checking in ios 10.2)
