### ISSUE TITLE
iOS 7 compatibility

### ISSUE THREAD

**Issue by kientux** [maxkonovalov/MKDropdownMenu#8]
Is there any reason why this library supports iOS8+ only? You didn't test it on iOS 7 or there is a non-compatible API used?

**Comment by maxkonovalov** [comment]
Hi @kientux 
I didn't test this myself, but I think it shouldn't have any issues with iOS 7. You can try adding the lib to your project and let me know of the outcome.

**Comment by MadanDipika** [comment]
Hi @maxkonovalov, 
  I have used this lib and found that there are just two properties  
1.@property(nonatomic) UIEdgeInsets layoutMargins of UIView.h                                        2.@property(getter=isActive) BOOL active of NSLayoutConstraint.h  
        that are stoping this being compatible with iOS 7. And just commenting their use, making the lib compatible with iOS 7 as well. Thanks :) :)

**Comment by maxkonovalov** [comment]
Hi @MadanDipika 
Thanks for pointing out these, I didn't plan to support iOS 7 anyway, so now we can be sure to leave the iOS 8 deployment target as it was initially.
