### ISSUE TITLE
Change  text on Head

### ISSUE THREAD

**Issue by Vietnd34** [maxkonovalov/MKDropdownMenu#9]
How to change text on head by selected component?

**Comment by manjuhere** [comment]
how did you do it?

**Comment by Vietnd34** [comment]
- (NSAttributedString *)dropdownMenu:(MKDropdownMenu *)dropdownMenu attributedTitleForSelectedComponent:(NSInteger)component{
return "title";
use this delegate.and when select a value.
- (void)dropdownMenu:(MKDropdownMenu *)dropdownMenu didSelectRow:(NSInteger)row inComponent:(NSInteger)component{
    [dropdownMenu reloadComponent:component];
}
